spring.application.name=iam-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/iam_service
spring.datasource.username=postgres
spring.datasource.password=matias2oo6
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.physical_naming_strategy=com.fragbyte.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

authorization.jwt.secret=TuSecretoJWTDeAlMenos32CaracteresDebeSerSeguro123!
authorization.jwt.expiration.days=1

iam.verification.enabled=false

iam.providers.google.client-id=

cors.allowed-origins=http://localhost:4200
